name: test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '^1.20'
      - name: List files for debugging
        run: ls -R
      - name: Copy config file
        run: mkdir -p ~/.config/jBalCompTools && cp testData/testConfig/config.toml ~/.config/jBalCompTools/config.toml

      - name: Run tests
        run: go test ./...
